relativeURLs = true
title = "Renato Puga"
theme = "academimal"
sectionPagesMenu = "main"
defaultContentLanguage = "en"

[params]
    shortbio = "Consultant Bioinformatician"
    logo = "renatopuga-face.png" 
